/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

/**
 *
 * @author Daniel Agudelo
 */
public class Consultar1 extends javax.swing.JFrame {

    /**
     * Creates new form Consultar1
     */
    public Consultar1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField1nombres = new javax.swing.JTextField();
        jTextField2apellidos = new javax.swing.JTextField();
        jTextField3cedula = new javax.swing.JTextField();
        jTextField4celular = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jTextField5direccion = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextField6correo = new javax.swing.JTextField();
        jTextField7telefonofijo = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextField8salariobase = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextField9valorhora = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jTextField10horasexn = new javax.swing.JTextField();
        jTextField11horasexd = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jTextField12valorexn = new javax.swing.JTextField();
        jTextField13valorexd = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jTextField14salariofinal = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jTextField15subtransporte = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 834, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 534, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Wide Latin", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 153, 102));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Consultar Empleado");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(270, 30, 420, 25);

        jLabel3.setFont(new java.awt.Font("Wide Latin", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText(" Nombres: ");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(0, 80, 150, 20);

        jLabel4.setFont(new java.awt.Font("Wide Latin", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Apellidos: ");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(0, 110, 150, 40);

        jLabel5.setFont(new java.awt.Font("Wide Latin", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Cedula:");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(0, 150, 150, 40);

        jLabel6.setFont(new java.awt.Font("Wide Latin", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Celular:");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(0, 190, 150, 30);

        jLabel7.setFont(new java.awt.Font("Wide Latin", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 153, 102));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Salario:");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(530, 350, 100, 40);

        jTextField1nombres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1nombresActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField1nombres);
        jTextField1nombres.setBounds(200, 82, 275, 20);
        jPanel2.add(jTextField2apellidos);
        jTextField2apellidos.setBounds(200, 122, 275, 20);
        jPanel2.add(jTextField3cedula);
        jTextField3cedula.setBounds(200, 160, 275, 20);

        jTextField4celular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4celularActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField4celular);
        jTextField4celular.setBounds(200, 197, 275, 20);

        jLabel8.setFont(new java.awt.Font("Wide Latin", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Area:");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(480, 90, 80, 14);

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Gerencia");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(575, 80, 100, 23);

        jButton2.setText("Administrativa");
        jPanel2.add(jButton2);
        jButton2.setBounds(680, 80, 120, 23);

        jButton3.setText("Planta");
        jPanel2.add(jButton3);
        jButton3.setBounds(810, 80, 80, 23);

        jLabel9.setFont(new java.awt.Font("Wide Latin", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Direccion:");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(480, 120, 150, 20);
        jPanel2.add(jTextField5direccion);
        jTextField5direccion.setBounds(650, 120, 244, 20);

        jLabel10.setFont(new java.awt.Font("Wide Latin", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Telefono:");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(480, 200, 150, 20);

        jLabel11.setFont(new java.awt.Font("Wide Latin", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("E-mail:");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(470, 160, 150, 20);

        jTextField6correo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6correoActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField6correo);
        jTextField6correo.setBounds(650, 160, 244, 20);
        jPanel2.add(jTextField7telefonofijo);
        jTextField7telefonofijo.setBounds(650, 200, 244, 20);

        jLabel12.setFont(new java.awt.Font("Wide Latin", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 153, 102));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("Valor Hora:");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(600, 230, 160, 40);
        jPanel2.add(jTextField8salariobase);
        jTextField8salariobase.setBounds(460, 240, 120, 20);

        jLabel13.setFont(new java.awt.Font("Wide Latin", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel13.setText("Nocturnas:");
        jPanel2.add(jLabel13);
        jLabel13.setBounds(580, 280, 150, 40);

        jTextField9valorhora.setEnabled(false);
        jTextField9valorhora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField9valorhoraActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField9valorhora);
        jTextField9valorhora.setBounds(780, 240, 110, 20);

        jLabel14.setFont(new java.awt.Font("Wide Latin", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel14.setText("Genero:");
        jPanel2.add(jLabel14);
        jLabel14.setBounds(50, 230, 100, 40);

        jLabel15.setFont(new java.awt.Font("Wide Latin", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 153, 102));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel15.setText("Salario Base:");
        jPanel2.add(jLabel15);
        jLabel15.setBounds(290, 230, 170, 40);

        jLabel16.setFont(new java.awt.Font("Wide Latin", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 255, 255));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel16.setText("Diurnas:");
        jPanel2.add(jLabel16);
        jLabel16.setBounds(350, 280, 110, 40);
        jPanel2.add(jTextField10horasexn);
        jTextField10horasexn.setBounds(750, 290, 65, 20);
        jPanel2.add(jTextField11horasexd);
        jTextField11horasexd.setBounds(500, 290, 65, 20);

        jLabel17.setFont(new java.awt.Font("Wide Latin", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 153, 102));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel17.setText("Horas extras:");
        jPanel2.add(jLabel17);
        jLabel17.setBounds(160, 280, 160, 40);

        jLabel18.setFont(new java.awt.Font("Wide Latin", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 255, 255));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel18.setText("Limpiar");
        jPanel2.add(jLabel18);
        jLabel18.setBounds(670, 490, 110, 40);

        jLabel19.setFont(new java.awt.Font("Wide Latin", 0, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 255, 255));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel19.setText("Diurna:");
        jPanel2.add(jLabel19);
        jLabel19.setBounds(350, 310, 110, 40);
        jPanel2.add(jTextField12valorexn);
        jTextField12valorexn.setBounds(750, 320, 65, 20);
        jPanel2.add(jTextField13valorexd);
        jTextField13valorexd.setBounds(500, 320, 65, 20);

        jLabel20.setFont(new java.awt.Font("Wide Latin", 0, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 153, 102));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel20.setText("Valor hora extra:");
        jPanel2.add(jLabel20);
        jLabel20.setBounds(110, 310, 210, 40);

        jTextField14salariofinal.setEnabled(false);
        jPanel2.add(jTextField14salariofinal);
        jTextField14salariofinal.setBounds(650, 360, 150, 20);

        jLabel21.setFont(new java.awt.Font("Wide Latin", 0, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 153, 102));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel21.setText("Subsidio Transporte:");
        jPanel2.add(jLabel21);
        jLabel21.setBounds(60, 350, 260, 40);

        jTextField15subtransporte.setEnabled(false);
        jPanel2.add(jTextField15subtransporte);
        jTextField15subtransporte.setBounds(350, 360, 150, 20);

        jLabel22.setFont(new java.awt.Font("Wide Latin", 0, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 255, 255));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel22.setText("Nocturna:");
        jPanel2.add(jLabel22);
        jLabel22.setBounds(580, 310, 150, 40);

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/limp.jpg"))); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton6);
        jButton6.setBounds(690, 410, 73, 70);

        jLabel24.setFont(new java.awt.Font("Wide Latin", 0, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 255, 255));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel24.setText("Volver al menu");
        jPanel2.add(jLabel24);
        jLabel24.setBounds(140, 490, 200, 40);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cons.jpg"))); // NOI18N
        jPanel2.add(jButton4);
        jButton4.setBounds(470, 410, 72, 70);

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/guar.jpg"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5);
        jButton5.setBounds(210, 410, 79, 70);

        jLabel25.setFont(new java.awt.Font("Wide Latin", 0, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 255, 255));
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel25.setText("Consultar");
        jPanel2.add(jLabel25);
        jLabel25.setBounds(400, 490, 160, 40);

        jComboBox1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleecionar", "Hombre", "Mujer" }));
        jComboBox1.setToolTipText("");
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel2.add(jComboBox1);
        jComboBox1.setBounds(190, 240, 110, 20);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(-10, 0, 940, 540);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1nombresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1nombresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1nombresActionPerformed

    private void jTextField4celularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4celularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4celularActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField6correoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6correoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6correoActionPerformed

    private void jTextField9valorhoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField9valorhoraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField9valorhoraActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed

     
        
        
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
     
       jTextField1nombres.setText(" ");
         jTextField2apellidos.setText(" ");
         jTextField3cedula.setText(" ");
         jTextField4celular.setText(" ");
         jTextField5direccion.setText(" ");
         jTextField6correo.setText(" ");
         jTextField7telefonofijo.setText(" ");
         jTextField8salariobase.setText(" ");
         jTextField11horasexd.setText(" ");
         jTextField10horasexn.setText(" ");
         jTextField12valorexn.setText(" ");
         jTextField13valorexd.setText(" ");
         jComboBox1.setSelectedIndex(0);

        
        
        
        
        
        
        
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
       
        
        Diseño1 ver= new Diseño1();
        ver.setVisible(true);
        ver.setSize(928, 575);
        this.setVisible(false);
        this.setLocationRelativeTo(null);
        
        
        
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Consultar1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Consultar1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Consultar1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Consultar1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Consultar1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField10horasexn;
    private javax.swing.JTextField jTextField11horasexd;
    private javax.swing.JTextField jTextField12valorexn;
    private javax.swing.JTextField jTextField13valorexd;
    private javax.swing.JTextField jTextField14salariofinal;
    private javax.swing.JTextField jTextField15subtransporte;
    private javax.swing.JTextField jTextField1nombres;
    private javax.swing.JTextField jTextField2apellidos;
    private javax.swing.JTextField jTextField3cedula;
    private javax.swing.JTextField jTextField4celular;
    private javax.swing.JTextField jTextField5direccion;
    private javax.swing.JTextField jTextField6correo;
    private javax.swing.JTextField jTextField7telefonofijo;
    private javax.swing.JTextField jTextField8salariobase;
    private javax.swing.JTextField jTextField9valorhora;
    // End of variables declaration//GEN-END:variables

 
}
